In [1]:
import numpy as np
arr = np.array([[0,1,-2.5,3],[4,5,6,7],[11.7,6.9,65,8],[9,10,11,108]])
print("Original array:\n",arr)
print("\nEvery other rows:arr[0:2:4]:\n",arr[0:2:4])

Original array:
 [[  0.    1.   -2.5   3. ]
 [  4.    5.    6.    7. ]
 [ 11.7   6.9  65.    8. ]
 [  9.   10.   11.  108. ]]

Every other rows:arr[0:2:4]:
 [[ 0.   1.  -2.5  3. ]]


In [2]:
temp = arr[:1,:2]
print("\nArray with first 1 row and 2 columns:arr[:1,:2]:\n",temp)


Array with first 1 row and 2 columns:arr[:1,:2]:
 [[0. 1.]]


In [3]:
temp = arr[[0,1,2,3],[3,2,4,5]]
print("\n Elements at indices (0,3),(1,2),(2,4),(3,5):\n",temp)

IndexError: index 4 is out of bounds for axis 1 with size 4

In [4]:
temp = arr[[0,1,2,3],[3,2,4,5]]
print("\n Elements at indices (0,3),(1,2),(2,4),""(3,5):\n",temp)

IndexError: index 4 is out of bounds for axis 1 with size 4

In [5]:
temp = arr[[0,1,2,3],[3,2,1,0]]
print("\n Elements at indices (0,3),(1,2),(2,4),""(3,5):\n",temp)


 Elements at indices (0,3),(1,2),(2,4),(3,5):
 [3.  6.  6.9 9. ]


In [6]:
cond = arr>2
temp = arr[cond]
print("\nElements greater than 2:\n",temp)


Elements greater than 2:
 [  3.    4.    5.    6.    7.   11.7   6.9  65.    8.    9.   10.   11.
 108. ]


In [7]:
arr = np.array([1,2,3,4,5,6,7])
print("\n Original Array:",arr)
print("\n Returns every other elements in the array:arr[::4]:",arr[::4])



 Original Array: [1 2 3 4 5 6 7]

 Returns every other elements in the array:arr[::4]: [1 5]


In [8]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print("\n Original arrays:\n",arr1,arr2)
print("\nJoined arrays:\n",arr)


 Original arrays:
 [1 2 3 4] [5 6 7 8]

Joined arrays:
 [1 2 3 4 5 6 7 8]


In [9]:
arr = np.hstack((arr1,arr2))
print("\nHorizontal Joining:\n",arr)


Horizontal Joining:
 [1 2 3 4 5 6 7 8]


In [10]:
arr = np.vstack((arr1,arr2))
print("\n Vertical joining:\n",arr)


 Vertical joining:
 [[1 2 3 4]
 [5 6 7 8]]


In [11]:
arr = np.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [12]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print("\nOriginal array:\n",arr)
print("\nSplitted array:\n",newarr)


Original array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]
