In [1]:
import numpy as np
a = np.array([1,2,3,4])
print("Array created using passed list:\n",a)

Array created using passed list:
 [1 2 3 4]


In [2]:
b = np.zeros((4,6))
print("\n An array initialized with all zeros:\n",b)


 An array initialized with all zeros:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
c = np.full((1,3),11)
print("\n An array initialized with all 11s\n",c)


 An array initialized with all 11s
 [[11 11 11]]


In [4]:
d = np.random.random((2,2))
print("\n A random array:\n",d)


 A random array:
 [[0.65786804 0.96141137]
 [0.78136903 0.73679626]]


In [5]:
e = np.arange(0,30,5)
print("\n A sequential array with steps of 5:\n",e)


 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)



Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array[4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
flarr = arr.flatten()
print("\nOriginal array:\n",arr)
print("Flattened array:\n",flarr)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
print("No of dimensions:",arr.ndim)

No of dimensions: 2


In [9]:
print("Shape of array:",arr.shape)
print("\nArray stores elements of type:",arr.dtype)


Shape of array: (3, 4)

Array stores elements of type: int32


In [10]:
newtype = arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)



Converted array elements:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Converted array type: float32
